import { Listing, MarketPrice } from '../types';

export const MOCK_LISTINGS: Listing[] = [
  {
    id: '1',
    cropName: 'Wheat',
    variety: 'Sharbati',
    pricePerQuintal: 2150,
    quantityQuintals: 50,
    state: 'Madhya Pradesh',
    district: 'Sehore',
    harvestDate: '2023-04-10',
    sellerName: 'Ramesh Kumar',
    description: 'High quality Sharbati wheat, golden grain. Naturally grown.',
    imageUrl: 'https://picsum.photos/400/300?random=1',
    isVerified: true,
  },
  {
    id: '2',
    cropName: 'Rice',
    variety: 'Basmati 1121',
    pricePerQuintal: 4200,
    quantityQuintals: 100,
    state: 'Punjab',
    district: 'Amritsar',
    harvestDate: '2023-10-15',
    sellerName: 'Gurdeep Singh',
    description: 'Premium aged Basmati rice. Long grain.',
    imageUrl: 'https://picsum.photos/400/300?random=2',
    isVerified: true,
  },
  {
    id: '3',
    cropName: 'Mustard',
    variety: 'Black',
    pricePerQuintal: 5400,
    quantityQuintals: 20,
    state: 'Rajasthan',
    district: 'Alwar',
    harvestDate: '2023-03-20',
    sellerName: 'Sunita Devi',
    description: 'Oil content above 40%. Cleaned and graded.',
    imageUrl: 'https://picsum.photos/400/300?random=3',
    isVerified: false,
  },
  {
    id: '4',
    cropName: 'Tomato',
    variety: 'Desi',
    pricePerQuintal: 1200,
    quantityQuintals: 10,
    state: 'Maharashtra',
    district: 'Nashik',
    harvestDate: '2023-12-01',
    sellerName: 'Vijay Patil',
    description: 'Fresh farm picked tomatoes.',
    imageUrl: 'https://picsum.photos/400/300?random=4',
    isVerified: true,
  },
  {
    id: '5',
    cropName: 'Cotton',
    variety: 'Long Staple',
    pricePerQuintal: 6100,
    quantityQuintals: 80,
    state: 'Gujarat',
    district: 'Rajkot',
    harvestDate: '2023-11-05',
    sellerName: 'Arjun Bhai',
    description: 'High quality cotton bales available.',
    imageUrl: 'https://picsum.photos/400/300?random=5',
    isVerified: true,
  },
];

export const MARKET_PRICES: MarketPrice[] = [
  {
    id: 'mp1',
    cropName: 'Wheat',
    minPrice: 2000,
    maxPrice: 2400,
    avgPrice: 2200,
    trend: 'stable',
    lastUpdated: '2023-10-25',
  },
  {
    id: 'mp2',
    cropName: 'Rice (Basmati)',
    minPrice: 3800,
    maxPrice: 4500,
    avgPrice: 4150,
    trend: 'up',
    lastUpdated: '2023-10-25',
  },
  {
    id: 'mp3',
    cropName: 'Mustard',
    minPrice: 5000,
    maxPrice: 5600,
    avgPrice: 5300,
    trend: 'down',
    lastUpdated: '2023-10-24',
  },
  {
    id: 'mp4',
    cropName: 'Onion',
    minPrice: 1500,
    maxPrice: 2800,
    avgPrice: 2100,
    trend: 'up',
    lastUpdated: '2023-10-26',
  },
  {
    id: 'mp5',
    cropName: 'Potato',
    minPrice: 800,
    maxPrice: 1200,
    avgPrice: 1000,
    trend: 'stable',
    lastUpdated: '2023-10-25',
  },
];
